version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalProductPassport
      MYSQL_USER: dpp
      MYSQL_PASSWORD: dpp123
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
