version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: digitalProductPassport
      MYSQL_USER: dpp
      MYSQL_PASSWORD: dpp123
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #command: bash -c "chmod 777 /docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
